### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by CCV-Edward** [HTuennermann/Vehicle-Detection-and-Tracking#1]
hi HTuennermann
    could you please give me some advice about how to get datasets

**Comment by HTuennermann** [comment]
I used the data which can now be found on the udacity repo:
https://github.com/udacity/CarND-Vehicle-Detection (https://s3.amazonaws.com/udacity-sdc/Vehicle_Tracking/vehicles.zip and
https://s3.amazonaws.com/udacity-sdc/Vehicle_Tracking/non-vehicles.zip). 
I will add the links in readme later
