### ISSUE TITLE
Problem with model 

### ISSUE THREAD

**Issue by maksimliubimov** [HTuennermann/Vehicle-Detection-and-Tracking#2]
I have problem with model of network when I use your instruction: 
ValueError: Error when checking target: expected flatten_1 to have shape (None, 1749) but got array with shape (162, 1)
I would be grateful you for help

**Comment by HTuennermann** [comment]
what version of tensorflow and keras do you have installed? There might be some issues with api changes in the newer versions. I am looking at updating this but did not yet find the time to do it.

**Comment by maksimliubimov** [comment]
I've installed keras 2.0.8 and tensorflow 1.3.0.  Which version do you have?

**Comment by HTuennermann** [comment]
I have just tested against the latest keras (and added a tf version) but i did not encounter this error. Do you have that error in training? In that case it is just a normal classifier make sure your y vector has the right shape (compare with my concrete example if necessary).

**Comment by maksimliubimov** [comment]
Thanks to you data I've found error in my training.Thank you so much
